INSERT INTO "Product"(id,name,price,createdAt,updatedAt) VALUES
('Laptop Gaming', 129999, datetime('now'), datetime('now')),
('Mouse Inalámbrico', 2999, datetime('now'), datetime('now')),
('Teclado Mecánico', 8999, datetime('now'), datetime('now')),
('Monitor 4K', 39999, datetime('now'), datetime('now')),
('Auriculares Bluetooth', 159.99, datetime('now'), datetime('now')),
('Smartphone', 69999, datetime('now'), datetime('now')),
('Tablet 10 pulgadas', 24999, datetime('now'), datetime('now')),
('Cámara Web HD', 7999, datetime('now'), datetime('now')),
('Disco SSD 1TB', 11999, datetime('now'), datetime('now')),
('Memoria RAM 16GB', 8999, datetime('now'), datetime('now')),
('Procesador Intel i7', 34999, datetime('now'), datetime('now')),
('Tarjeta Gráfica RTX', 79999, datetime('now'), datetime('now')),
('Altavoces Bluetooth', 4999, datetime('now'), datetime('now')),
('Cable USB-C', 1999, datetime('now'), datetime('now')),
('Cargador Portátil', 3999, datetime('now'), datetime('now')),
('Router WiFi 6', 12999, datetime('now'), datetime('now')),
('Impresora Láser', 17999, datetime('now'), datetime('now')),
('Scanner Documentos', 8999, datetime('now'), datetime('now')),
('Micrófono USB', 5999, datetime('now'), datetime('now')),
('Soporte Monitor', 3499, datetime('now'), datetime('now')),
('Mousepad Gaming', 2499, datetime('now'), datetime('now')),
('Silla Gaming', 29999, datetime('now'), datetime('now')),
('Escritorio Gaming', 19999, datetime('now'), datetime('now')),
('Lámpara LED', 4599, datetime('now'), datetime('now')),
('Hub USB 3.0', 2999, datetime('now'), datetime('now')),
('Adaptador HDMI', 1499, datetime('now'), datetime('now')),
('Dock Station', 14999, datetime('now'), datetime('now')),
('Ventilador CPU', 4999, datetime('now'), datetime('now')),
('Pasta Térmica', 999, datetime('now'), datetime('now')),
('Fuente Poder 750W', 8999, datetime('now'), datetime('now')),
('Motherboard ATX', 15999, datetime('now'), datetime('now')),
('Gabinete Gaming', 7999, datetime('now'), datetime('now')),
('Disco HDD 2TB', 6999, datetime('now'), datetime('now')),
('Memoria USB 64GB', 1999, datetime('now'), datetime('now')),
('Tarjeta MicroSD 128GB', 2499, datetime('now'), datetime('now')),
('Batería Externa 10000mAh', 3499, datetime('now'), datetime('now')),
('Cable HDMI 2m', 1299, datetime('now'), datetime('now')),
('Cable Ethernet 5m', 899, datetime('now'), datetime('now')),
('Switch Ethernet 8 puertos', 3999, datetime('now'), datetime('now')),
('Repetidor WiFi', 4999, datetime('now'), datetime('now')),
('Cámara Seguridad WiFi', 8999, datetime('now'), datetime('now')),
('Timbre Inteligente', 12999, datetime('now'), datetime('now')),
('Cerradura Inteligente', 19999, datetime('now'), datetime('now')),
('Termostato Inteligente', 14999, datetime('now'), datetime('now')),
('Bombilla LED Inteligente', 1999, datetime('now'), datetime('now')),
('Enchufe Inteligente', 1499, datetime('now'), datetime('now')),
('Sensor Movimiento', 2999, datetime('now'), datetime('now')),
('Detector Humo WiFi', 7999, datetime('now'), datetime('now')),
('Aspiradora Robot', 29999, datetime('now'), datetime('now')),
('Purificador Aire', 14999, datetime('now'), datetime('now')),
('Humidificador Ultrasónico', 5999, datetime('now'), datetime('now')),
('Difusor Aromas', 3999, datetime('now'), datetime('now')),
('Báscula Inteligente', 4999, datetime('now'), datetime('now')),
('Reloj Inteligente', 19999, datetime('now'), datetime('now')),
('Pulsera Fitness', 7999, datetime('now'), datetime('now')),
('Auriculares Deportivos', 8999, datetime('now'), datetime('now')),
('Botella Agua Inteligente', 4499, datetime('now'), datetime('now')),
('Mochila Antirrobo', 6999, datetime('now'), datetime('now')),
('Cargador Inalámbrico', 2999, datetime('now'), datetime('now')),
('Soporte Móvil Coche', 1999, datetime('now'), datetime('now')),
('Dashcam 4K', 11999, datetime('now'), datetime('now')),
('GPS Navegador', 8999, datetime('now'), datetime('now')),
('Transmisor FM Bluetooth', 2499, datetime('now'), datetime('now')),
('Adaptador Bluetooth Coche', 3499, datetime('now'), datetime('now')),
('Cámara Acción 4K', 15999, datetime('now'), datetime('now')),
('Gimbal Smartphone', 9999, datetime('now'), datetime('now')),
('Trípode Carbono', 7999, datetime('now'), datetime('now')),
('Lente Macro Móvil', 2999, datetime('now'), datetime('now')),
('Ring Light LED', 3999, datetime('now'), datetime('now')),
('Softbox Iluminación', 5999, datetime('now'), datetime('now')),
('Micrófono Lavalier', 2499, datetime('now'), datetime('now')),
('Grabadora Digital', 6999, datetime('now'), datetime('now')),
('Mezcladora Audio', 14999, datetime('now'), datetime('now')),
('Interface Audio USB', 9999, datetime('now'), datetime('now')),
('Monitor Estudio', 19999, datetime('now'), datetime('now')),
('Soporte Micrófono', 3499, datetime('now'), datetime('now')),
('Cable XLR 3m', 1999, datetime('now'), datetime('now')),
('Pedal Sustain', 2499, datetime('now'), datetime('now')),
('Teclado MIDI 61 teclas', 12999, datetime('now'), datetime('now')),
('Controlador DJ', 19999, datetime('now'), datetime('now')),
('Auriculares DJ', 8999, datetime('now'), datetime('now')),
('Amplificador Guitarra', 14999, datetime('now'), datetime('now')),
('Pedal Efectos Guitarra', 7999, datetime('now'), datetime('now')),
('Cuerdas Guitarra Eléctrica', 1299, datetime('now'), datetime('now')),
('Púas Guitarra Set', 499, datetime('now'), datetime('now')),
('Soporte Guitarra', 1999, datetime('now'), datetime('now')),
('Afinador Cromático', 1499, datetime('now'), datetime('now')),
('Metrónomo Digital', 2499, datetime('now'), datetime('now')),
('Libro Teoría Musical', 2999, datetime('now'), datetime('now')),
('Atril Partituras', 3499, datetime('now'), datetime('now')),
('Funda Laptop 15.6', 2499, datetime('now'), datetime('now')),
('Mochila Laptop Gaming', 5999, datetime('now'), datetime('now')),
('Maletín Ejecutivo', 8999, datetime('now'), datetime('now')),
('Organizador Cables', 1499, datetime('now'), datetime('now')),
('Soporte Tablet Cama', 2999, datetime('now'), datetime('now')),
('Lupa LED Escritorio', 3999, datetime('now'), datetime('now')),
('Calculadora Científica', 1999, datetime('now'), datetime('now')),
('Pizarra Magnética', 4999, datetime('now'), datetime('now')),
('Marcadores Pizarra Set', 999, datetime('now'), datetime('now')),
('Borrador Pizarra', 599, datetime('now'), datetime('now'));